-- Accurate portfolio content for hallworld.
-- Replaces the fabricated seed from 0002 with data verified directly with the owner:
-- real identity/title, anonymized private engagements (names withheld), public bounty
-- results (program name withheld), self-taught education via PortSwigger labs,
-- and only the tools actually used (Burp Suite, IDA Pro, Cheat Engine).

UPDATE portfolio_content SET
  data_json = '{"identity":{"name":"hallworld","title":"Security Researcher & Developer","location":"Doha, Qatar","email":"hallworld@atomicmail.io"},"links":[{"label":"GitHub","url":"https://github.com/coqs"},{"label":"HackerOne","url":"https://hackerone.com/hallworld"}],"summary":"Fullstack developer (JS/React/Node) focused on web application security. Validated Medium + Critical on public bug bounties, found account-takeover and admin-access flaws in production apps across Qatar and the UAE.","experience":[{"role":"Independent Security Researcher","organization":"Public bug bounty programs","dates":"Aug 2026 — Present","bullets":["Validated 1 Medium and 1 Critical (pending) on a public bug bounty program (program name withheld).","7 duplicate reports before the first valid finding — persistence through a competitive disclosure process.","Reconnaissance, vulnerability validation, and clear engagement-style reporting."]},{"role":"Private Security Engagements","organization":"Qatar & UAE — names withheld","dates":"2026 — Present","bullets":["Document-management platform, Qatar (~80k users): account takeover, admin dashboard access, mass data-exposure potential.","Fashion retail app, Qatar: admin dashboard access and mass data-exposure potential.","Fashion retail app, UAE: admin dashboard access and mass data-exposure potential."]},{"role":"Independent Developer","organization":"Tools and experiments","dates":"2025 — Present","bullets":["YAFC — Yet Another File Cleaner: Windows file-management tool with resumable sessions, native folder picking, media/document/archive previews, and a keyboard-driven keep/delete flow.","TryOn: AI virtual try-on built on Gemini Nano Banana, with a clean Node.js backend.","Game reverse-engineering and automation utilities (IDA Pro, Cheat Engine)."]}],"education":[{"school":"Cybersecurity — self-taught","details":"PortSwigger Web Security Academy labs; web application security, network security, programming, and cryptography fundamentals","dates":"2026 — Present"}],"skills":[{"label":"Security","value":"Web application security, OWASP Top 10, reconnaissance, exploitation, responsible disclosure"},{"label":"Development","value":"JavaScript, React, Node.js, Next.js, HTML/CSS, basic Python, basic C++"},{"label":"Tools","value":"Burp Suite, IDA Pro, Cheat Engine, GitHub, REST APIs, Cloudflare Workers"}],"activities":["Reverse engineering games","Bug bounty research","AI and robotics competitions"],"awards":["1st place — AI & Robotics 2026 Qatar competition, line-following challenge"],"certifications":[]}',
  updated_at = '2026-08-09T00:00:00.000Z'
WHERE id = 1;
