const json = (data, status = 200, extra = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': status === 200 ? 'public, max-age=30' : 'no-store', ...extra } })
const now = () => new Date().toISOString()
const encoder = new TextEncoder()
const decoder = new TextDecoder()

async function digest(value) { const hash = await crypto.subtle.digest('SHA-256', encoder.encode(value)); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, '0')).join('') }
async function hmac(value, secret) { const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const signature = await crypto.subtle.sign('HMAC', key, encoder.encode(value)); return [...new Uint8Array(signature)].map((byte) => byte.toString(16).padStart(2, '0')).join('') }
function b64(value) { return btoa(unescape(encodeURIComponent(value))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '') }
function unb64(value) { return decodeURIComponent(escape(atob(value.replaceAll('-', '+').replaceAll('_', '/') + '='.repeat((4 - value.length % 4) % 4)))) }
async function createSession(secret) { const payload = b64(JSON.stringify({ exp: Date.now() + 1000 * 60 * 60 * 24 * 7 })); return `${payload}.${await hmac(payload, secret)}` }
async function validSession(request, secret) { const cookie = request.headers.get('cookie')?.split(';').map((item) => item.trim()).find((item) => item.startsWith('hw_session=')); if (!cookie) return false; const token = cookie.slice('hw_session='.length); const [payload, signature] = token.split('.'); if (!payload || !signature || signature !== await hmac(payload, secret)) return false; try { return JSON.parse(unb64(payload)).exp > Date.now() } catch { return false } }
function cookie(value, maxAge, secure = true) { return `hw_session=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; ${secure ? 'Secure; ' : ''}SameSite=Lax` }
function cleanProject(row) { return { ...row, tech: JSON.parse(row.tech_json || '[]'), featured: Boolean(row.featured) } }
function cleanPost(row) { return { ...row, tags: JSON.parse(row.tags_json || '[]') } }
async function body(request) { try { return await request.json() } catch { throw new Error('Invalid JSON body') } }
function required(value, name) { if (typeof value !== 'string' || !value.trim()) throw new Error(`${name} is required`) }
async function requireAdmin(request, env) { if (!env.ADMIN_PASSWORD || !env.SESSION_SECRET || !(await validSession(request, env.SESSION_SECRET))) throw new Error('Unauthorized') }

export default {
  async fetch(request, env) {
    const url = new URL(request.url)
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: { 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS', 'access-control-allow-headers': 'content-type', 'access-control-max-age': '86400' } })
    try {
      if (!env.DB) return json({ error: 'D1 is not configured.' }, 503)
      if (url.pathname === '/api/portfolio' && request.method === 'GET') { const row = await env.DB.prepare('SELECT data_json FROM portfolio_content WHERE id = 1').first(); return json(row ? JSON.parse(row.data_json) : {}) }
      if (url.pathname === '/api/projects' && request.method === 'GET') { const { results } = await env.DB.prepare('SELECT * FROM projects ORDER BY featured DESC, sort_order ASC, id ASC').all(); return json(results.map(cleanProject)) }
      if (url.pathname === '/api/posts' && request.method === 'GET') { const { results } = await env.DB.prepare("SELECT * FROM posts WHERE status = 'published' ORDER BY published_at DESC, id DESC").all(); return json(results.map(cleanPost)) }
      if (url.pathname.startsWith('/api/posts/') && request.method === 'GET') { const slug = decodeURIComponent(url.pathname.split('/').pop()); const row = await env.DB.prepare("SELECT * FROM posts WHERE slug = ? AND status = 'published'").bind(slug).first(); return row ? json(cleanPost(row)) : json({ error: 'Post not found' }, 404) }
      if (url.pathname === '/api/auth/login' && request.method === 'POST') { const input = await body(request); required(input.password, 'Password'); const expected = await digest(env.ADMIN_PASSWORD); const actual = await digest(input.password); if (expected !== actual) return json({ error: 'Invalid password' }, 401); const token = await createSession(env.SESSION_SECRET); return json({ ok: true }, 200, { 'set-cookie': cookie(token, 60 * 60 * 24 * 7, url.protocol === 'https:') }) }
      if (url.pathname === '/api/auth/session' && request.method === 'GET') return (await validSession(request, env.SESSION_SECRET || '')) ? json({ authenticated: true }) : json({ authenticated: false }, 401)
      if (url.pathname === '/api/auth/logout' && request.method === 'POST') return json({ ok: true }, 200, { 'set-cookie': cookie('', 0, url.protocol === 'https:') })
      await requireAdmin(request, env)
      if (url.pathname === '/api/admin/portfolio' && request.method === 'PUT') { const input = await body(request); await env.DB.prepare('INSERT INTO portfolio_content (id, data_json, updated_at) VALUES (1, ?, ?) ON CONFLICT(id) DO UPDATE SET data_json = excluded.data_json, updated_at = excluded.updated_at').bind(JSON.stringify(input), now()).run(); return json(input) }
      if (url.pathname === '/api/admin/projects' && request.method === 'POST') { const input = await body(request); ['slug', 'title', 'summary'].forEach((name) => required(input[name], name)); const result = await env.DB.prepare('INSERT INTO projects (slug, title, summary, details, tech_json, url, featured, sort_order, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING *').bind(input.slug.trim(), input.title.trim(), input.summary.trim(), input.details || '', JSON.stringify(input.tech || []), input.url || '', input.featured ? 1 : 0, input.sort_order || 0, now()).first(); return json(cleanProject(result), 201) }
      if (url.pathname.startsWith('/api/admin/projects/')) { const id = Number(url.pathname.split('/').pop()); if (request.method === 'DELETE') { await env.DB.prepare('DELETE FROM projects WHERE id = ?').bind(id).run(); return json({ ok: true }) } if (request.method === 'PATCH') { const input = await body(request); const result = await env.DB.prepare('UPDATE projects SET slug = ?, title = ?, summary = ?, details = ?, tech_json = ?, url = ?, featured = ?, sort_order = ?, updated_at = ? WHERE id = ? RETURNING *').bind(input.slug, input.title, input.summary, input.details || '', JSON.stringify(input.tech || []), input.url || '', input.featured ? 1 : 0, input.sort_order || 0, now(), id).first(); return result ? json(cleanProject(result)) : json({ error: 'Project not found' }, 404) } }
      if (url.pathname === '/api/admin/posts' && request.method === 'POST') { const input = await body(request); ['slug', 'title'].forEach((name) => required(input[name], name)); const publishedAt = input.status === 'published' ? now() : null; const result = await env.DB.prepare('INSERT INTO posts (slug, title, excerpt, body_markdown, tags_json, status, published_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING *').bind(input.slug.trim(), input.title.trim(), input.excerpt || '', input.body_markdown || '', JSON.stringify(input.tags || []), input.status === 'published' ? 'published' : 'draft', publishedAt, now()).first(); return json(cleanPost(result), 201) }
      if (url.pathname.startsWith('/api/admin/posts/')) { const id = Number(url.pathname.split('/').pop()); if (request.method === 'DELETE') { await env.DB.prepare('DELETE FROM posts WHERE id = ?').bind(id).run(); return json({ ok: true }) } if (request.method === 'PATCH') { const input = await body(request); const status = input.status === 'published' ? 'published' : 'draft'; const result = await env.DB.prepare('UPDATE posts SET slug = ?, title = ?, excerpt = ?, body_markdown = ?, tags_json = ?, status = ?, published_at = CASE WHEN ? = \'published\' AND published_at IS NULL THEN ? ELSE published_at END, updated_at = ? WHERE id = ? RETURNING *').bind(input.slug, input.title, input.excerpt || '', input.body_markdown || '', JSON.stringify(input.tags || []), status, status, now(), now(), id).first(); return result ? json(cleanPost(result)) : json({ error: 'Post not found' }, 404) } }
      return json({ error: 'Not found' }, 404)
    } catch (error) { return json({ error: error.message === 'Unauthorized' ? 'Unauthorized' : error.message || 'Server error' }, error.message === 'Unauthorized' ? 401 : 400) }
  },
}
